lea:
  modulesDir: ../modules

  allowlist:
    senders:
      - "@alice:example.org"
      - "@bob:example.org"
    groups:
      - "!roomid:example.org"

  matrix:
    homeserverUrl: "https://matrix.example.org"
    accessToken: "syt_..."
    userId: "@lea:example.org"
